# Generated by Django 5.0.2 on 2024-04-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='Language',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('sp', 'Spanish'), ('pg', 'Portuguese')], default='en', help_text='Language', max_length=2),
        ),
    ]
